{% set name = "sqlalchemy-databricks" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-databricks-{{ version }}.tar.gz
  sha256: d6efc02643962a1841eeb9139b942efc0246440c9cef3e7f7ebb3ea8d38eb5c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - pyhive >=0,<1
    - sqlalchemy >=1,<2
    - databricks-sql-connector >=2,<3

test:
  imports:
    - sqlalchemy_databricks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/crflynn/sqlalchemy-databricks
  summary: SQLAlchemy Dialect for Databricks
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
